"""
Job state.

An in-process dictionary behind an asyncio lock. No database, no Redis.

WHY THAT IS THE RIGHT CHOICE HERE, AND WHERE IT BREAKS

A job lives for about ten seconds and is interesting for about a minute after
that. Its result is a few hundred kilobytes of JSON that can be regenerated by
re-uploading the video. Persisting that to a database would add a dependency, a
schema, a migration story and a backup story, to protect data that is cheap to
recreate and that nobody will ask for tomorrow.

The honest limits, which belong in the README rather than being discovered:

  * Jobs do not survive a restart. A deploy during processing loses the job.
  * State is process-local, so this cannot be scaled to two replicas without
    replacing this module. The seam is this file and nothing else.
  * Memory is bounded by `max_jobs_retained`, not by uptime.

WHY IDS ARE RANDOM

There is no authentication -- a reviewer must be able to open the URL and
upload a video with no sign-up. So the id IS the capability: knowing it is what
grants access to the result. `secrets.token_urlsafe` gives 32 bytes of
cryptographically-random id, which is not enumerable. A sequential integer id
would let anyone read every result by counting.

And an unknown id returns 404, never 403. A 403 would confirm that an id exists,
which is precisely the fact worth hiding.
"""

from __future__ import annotations

import asyncio
import secrets
from collections import OrderedDict
from dataclasses import dataclass, field
from datetime import datetime, timezone

from app.config import settings
from app.schema import FAILURE_MESSAGES, FailureReason, JobStatus, SlamResult


def _now() -> str:
    """UTC ISO-8601. UTC everywhere avoids a class of timezone bugs later."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class Job:
    """One uploaded video and its progress."""

    id: str
    filename: str
    size_bytes: int
    status: JobStatus = JobStatus.QUEUED

    # Coarse progress for the UI: which stage, and how far through the frames.
    stage: str = "queued"
    frames_total: int = 0
    frames_done: int = 0

    result: SlamResult | None = None
    timing: dict | None = None

    failure_reason: FailureReason | None = None
    failure_detail: str = ""

    created_at: str = field(default_factory=_now)
    finished_at: str | None = None

    def summary(self) -> dict:
        """
        Progress without the payload.

        The client polls this roughly once a second. The result carries
        thousands of 3D points, and re-sending them on every poll would waste
        most of the bandwidth of the whole exchange, so polling asks for the
        summary and fetches the full result exactly once, when status is done.
        """
        return {
            "job_id": self.id,
            "status": self.status.value,
            "stage": self.stage,
            "frames_total": self.frames_total,
            "frames_done": self.frames_done,
            "progress": (
                round(self.frames_done / self.frames_total, 3)
                if self.frames_total
                else 0.0
            ),
            "filename": self.filename,
            "created_at": self.created_at,
            "finished_at": self.finished_at,
            "failure_reason": self.failure_reason.value if self.failure_reason else None,
            "failure_message": (
                FAILURE_MESSAGES.get(self.failure_reason) if self.failure_reason else None
            ),
            "failure_detail": self.failure_detail or None,
        }

    def to_dict(self) -> dict:
        """Everything, including the reconstruction and the timing breakdown."""
        return {
            **self.summary(),
            "result": self.result.to_dict() if self.result else None,
            "timing": self.timing,
        }


class JobStore:
    """
    Async-safe job registry.

    The lock is not paranoia. FastAPI serves polls concurrently with the worker
    task that mutates jobs, all on one event loop; without a lock a poll could
    observe a half-updated job. The critical sections are all dictionary
    operations, so holding it is measured in microseconds.
    """

    def __init__(self) -> None:
        # OrderedDict so the oldest job is cheap to identify when pruning.
        self._jobs: "OrderedDict[str, Job]" = OrderedDict()
        self._lock = asyncio.Lock()

    async def create(self, filename: str, size_bytes: int) -> Job:
        job = Job(
            id=secrets.token_urlsafe(24),
            filename=filename,
            size_bytes=size_bytes,
        )
        async with self._lock:
            self._jobs[job.id] = job
            self._prune_locked()
        return job

    def _prune_locked(self) -> None:
        """
        Drop the oldest jobs past the retention cap.

        Called with the lock held. Without this the process grows for as long
        as it runs, and a long-lived server eventually dies of a slow leak that
        looks like a mystery rather than a policy.
        """
        while len(self._jobs) > settings.max_jobs_retained:
            self._jobs.popitem(last=False)

    async def get(self, job_id: str) -> Job | None:
        async with self._lock:
            return self._jobs.get(job_id)

    async def update(self, job_id: str, **fields) -> None:
        """Apply field updates to a job. Silently ignores an evicted job."""
        async with self._lock:
            job = self._jobs.get(job_id)
            if job is None:
                return
            for key, value in fields.items():
                setattr(job, key, value)

    async def set_progress(self, job_id: str, stage: str, done: int, total: int) -> None:
        await self.update(job_id, stage=stage, frames_done=done, frames_total=total)

    async def finish(self, job_id: str, result: SlamResult, timing: dict) -> None:
        # Snap frames_done to frames_total. The pipeline reports progress
        # BEFORE doing each frame's work, so the last report is n-1 and a
        # finished job would otherwise display 97% forever.
        async with self._lock:
            job = self._jobs.get(job_id)
            if job is not None and job.frames_total:
                job.frames_done = job.frames_total
        await self.update(
            job_id,
            status=JobStatus.DONE,
            stage="done",
            result=result,
            timing=timing,
            finished_at=_now(),
        )

    async def fail(
        self,
        job_id: str,
        reason: FailureReason,
        detail: str = "",
        timing: dict | None = None,
    ) -> None:
        await self.update(
            job_id,
            status=JobStatus.FAILED,
            stage="failed",
            failure_reason=reason,
            failure_detail=detail,
            timing=timing,
            finished_at=_now(),
        )

    async def count(self) -> int:
        async with self._lock:
            return len(self._jobs)


store = JobStore()
